## 2.Numpy 연산
연산을 통한 결과

In [1]:
import numpy as np
t_a=np.arange(1,11)
t_a.sum()

55

In [2]:
t_a=np.arange(1,13).reshape(3,4)
t_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

고차원에서의 출발로 고차원의 축을 이야기한다

In [3]:
t_a.sum(axis=0)#2

array([15, 18, 21, 24])

In [4]:
t_a.sum(axis=1)#1

array([10, 26, 42])

In [5]:
t_a_2=np.array([t_a,t_a,t_a])
t_a_2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [6]:
t_a_2.shape

(3, 3, 4)

In [7]:
t_a_2.sum(axis=0)#3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [8]:
t_a_2.sum(axis=1)#2

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [9]:
t_a_2.sum(axis=2)#1

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [10]:
v_a=np.array([1,2,3])
v_a_1=np.array([4,5,6])
np.vstack((v_a,v_a_1))

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
v_a=np.array([[1,2,3],[1,2,3]])
v_a_1=np.array([4,5,6])
np.vstack((v_a,v_a_1))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
v_a=np.array([[1,2,3],[1,2,3]])
v_a_1=np.array([4,5,6])
np.vstack((v_a,v_a_1)).T

array([[1, 1, 4],
       [2, 2, 5],
       [3, 3, 6]])

In [13]:
h_1=np.array([1,1,1]).T
h_1

array([1, 1, 1])

In [14]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [16]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [19]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [20]:
x==x

array([[ True,  True,  True],
       [ True,  True,  True]])

In [21]:
#주어진 데이터로 bmi출력
heights=np.array([1.83, 1.76, 1.69, 1.86, 1.77, 1.73])
weights = np.array([86, 74, 59, 95, 80, 68])
bmi=weights/(heights**2)
bmi

array([25.68007405, 23.88946281, 20.65754   , 27.45982194, 25.53544639,
       22.72043837])

In [22]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(1,7).reshape(3,2)
#반드시 가로와 새로의 개수일치
np.dot(x,y)
#위아래 식 같은말이다
x.dot(y)

array([[22, 28],
       [49, 64]])

In [23]:
x+1

array([[2, 3, 4],
       [5, 6, 7]])

In [24]:
x=np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
v=np.array([10,20,30])
v

array([10, 20, 30])

In [26]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [27]:
v2=np.array([1,2,3,4]).reshape(-1,1)
v2

array([[1],
       [2],
       [3],
       [4]])

In [28]:
x+v2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [29]:
v+v2

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [30]:
x=np.arange(3,10)
x

array([3, 4, 5, 6, 7, 8, 9])

In [31]:
(x>5)

array([False, False, False,  True,  True,  True,  True])

In [32]:
(x>5).all()

False

In [33]:
(x>5).any()

True

In [34]:
(x<1).all()

False

In [35]:
(x<1).any()

False

In [36]:
(x>2).all()

True

In [37]:
(x>2).any()

True

In [38]:
#난수를 0~100을 이용하여 100명의 학생들의 점수를 만들고,조건에 맞는프로그램 만드시오
#1. 100명의 평균이 50점이상이면 전원 통과출력
x=np.random.randint(0,100,100)
if np.mean(x)>=50:
  print("전원 통과")
if np.all(x>=50):
  print("학년 1등")
if np.any(x>=50):
  print("전교1등반")

전교1등반


In [39]:
x=np.array([1,2,3,4,5,1])
np.where(x==1,10,20)

array([10, 20, 20, 20, 20, 10])

In [40]:
x=np.array([1,2,3,4,5,1])
np.where(x==1,'10','20')

array(['10', '20', '20', '20', '20', '10'], dtype='<U2')

In [41]:
d=np.array([1,5,3,7,2,8,4])
np.argsort(d)#가장작은값부터 순서대로 인덱스 리턴
np.argmax(d)#큰값 인덱스 리턴
np.argmin(d)#작은값 인덱스 리턴

0

In [42]:
d>=5

array([False,  True, False,  True, False,  True, False])

In [43]:
d[d>=5]

array([5, 7, 8])

In [44]:
d.shape

(7,)

In [45]:
x=np.arange(1,11)
l=np.array([0,5,9,0,0,0])
x[l]

array([ 1,  6, 10,  1,  1,  1])

In [46]:
x=x.reshape(2,-1)
i_1=np.array([0,1])
i_0=np.array([1,0])
print(x)
x[i_0,i_1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([6, 2])

In [47]:
x_l=np.array([x,x,x])
x_l

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [48]:
x_l[:,:,:4]

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]])