In [1]:
#1. data수집
import pandas as pd
import numpy as np
data=pd.read_csv('data1_all.csv')
data_X=data[['Weight','Length','Diagonal','Height','Width']].to_numpy()
data_Y=data['Name'].to_numpy()

#2. data전처리
from sklearn.preprocessing import StandardScaler
ss=StandardScaler().fit(data_X)
data_X=ss.transform(data_X)

#3. data분리
from sklearn.model_selection import train_test_split
t_x,tt_x,t_y,tt_y= train_test_split(data_X,data_Y,random_state=42)
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=20,max_iter=1000) #다중분류용
lr.fit(t_x,t_y)
lr.score(t_x,t_y),lr.score(tt_x,tt_y)
d=lr.decision_function(t_x[:1])
from scipy.special import softmax #다중분류는 softmax를 사용하여 확률계산
np.around(softmax(d))

array([[1., 0., 0., 0., 0., 0., 0.]])

In [2]:
i=(t_y == 'A')|(t_y=='G') # |:and
b_t_x=t_x[i]
b_t_y=t_y[i]
lr = LogisticRegression()
lr.fit(b_t_x,b_t_y)

LogisticRegression()

In [3]:
lr.coef_, lr.intercept_

(array([[-0.41981254, -0.60056128, -0.68786241, -1.00159093, -0.74532495]]),
 array([-2.1898649]))

In [4]:
d=lr.decision_function(b_t_x[:1]) #decision_function 학습된 공식을 꺼냄, 선으로 그리는 함수
d

array([-5.96982853])

In [5]:
from scipy.special import expit #역함수, 이중분류는 시드모이드 함수를 사용하여 확률계산
expit(d) #로지스틱 함수 - 로짓함수의 역함수

array([0.00254817])