문서로드->문장토큰->단어토큰->정수인코딩->패딩

In [1]:
from konlpy.corpus import kolaw
t_data = kolaw.open('constitution.txt')
t_data.name

'C:\\Users\\user\\anaconda3\\Lib\\site-packages\\konlpy/data/corpus/kolaw/constitution.txt'

In [2]:
from soynlp import DoublespaceLineCorpus
t_data = DoublespaceLineCorpus(t_data.name,iter_sent=True)

In [3]:
from konlpy.tag import Okt
from tensorflow.keras.preprocessing.text import Tokenizer
tw1 = Okt()

In [4]:
s_data =[]
for w in t_data:
    d=tw1.nouns(w)
    d=[i for i in d if len(i)>1]
    s_data.append(d)
s_data

[['대한민국', '헌법'],
 ['유구',
  '역사',
  '전통',
  '우리',
  '국민',
  '운동',
  '건립',
  '대한민국',
  '임시정부',
  '통과',
  '불의',
  '항거',
  '민주',
  '이념',
  '계승',
  '조국',
  '민주',
  '개혁',
  '평화',
  '통일',
  '사명',
  '각하',
  '정의',
  '인도',
  '동포',
  '로써',
  '민족',
  '단결',
  '공고',
  '모든',
  '사회',
  '폐습',
  '불의',
  '타파',
  '자율',
  '조화',
  '바탕',
  '자유민주',
  '질서',
  '더욱',
  '정치',
  '경제',
  '사회',
  '문화',
  '모든',
  '영역',
  '각인',
  '기회',
  '능력',
  '최고',
  '도로',
  '발휘',
  '자유',
  '권리',
  '책임',
  '의무',
  '완수',
  '국민',
  '생활',
  '향상',
  '기하',
  '항구',
  '세계',
  '평화',
  '인류',
  '공영',
  '이바지',
  '우리',
  '우리',
  '자손',
  '안전',
  '자유',
  '행복',
  '확보',
  '다짐',
  '제정',
  '개정',
  '헌법',
  '이제',
  '국회',
  '의결',
  '국민투표',
  '개정'],
 [],
 ['대한민국', '민주공화국'],
 ['대한민국', '주권', '국민', '모든', '권력', '국민'],
 ['대한민국', '국민', '요건', '법률'],
 ['국가', '법률', '재외국민', '보호', '의무'],
 ['대한민국', '영토', '한반도', '부속', '도서'],
 ['대한민국', '통일', '지향', '자유민주', '질서', '입각', '평화', '통일', '정책', '수립', '추진'],
 ['대한민국', '국제', '평화', '유지', '노력', '침략', '전쟁', '부인'],
 ['국군', '국가', '안전

In [5]:
ck_t=Tokenizer()
ck_t.fit_on_texts(s_data)
ck_t.index_word

{1: '법률',
 2: '대통령',
 3: '국가',
 4: '국회',
 5: '국민',
 6: '헌법',
 7: '모든',
 8: '기타',
 9: '사항',
 10: '권리',
 11: '의원',
 12: '자유',
 13: '정부',
 14: '선거',
 15: '임명',
 16: '직무',
 17: '국무총리',
 18: '경제',
 19: '의무',
 20: '조직',
 21: '국회의원',
 22: '임기',
 23: '의결',
 24: '공무원',
 25: '경우',
 26: '이상',
 27: '국무위원',
 28: '대법원',
 29: '범위',
 30: '법관',
 31: '보호',
 32: '정책',
 33: '정당',
 34: '헌법재판소',
 35: '재적',
 36: '회의',
 37: '항의',
 38: '관리',
 39: '노력',
 40: '보장',
 41: '거나',
 42: '요구',
 43: '법원',
 44: '집회',
 45: '과반수',
 46: '출석',
 47: '찬성',
 48: '대한민국',
 49: '조약',
 50: '다만',
 51: '재판',
 52: '동의',
 53: '탄핵',
 54: '권한',
 55: '안전보장',
 56: '공포',
 57: '대한',
 58: '심판',
 59: '시행',
 60: '재판관',
 61: '위원',
 62: '정치',
 63: '효력',
 64: '대하',
 65: '체포',
 66: '절차',
 67: '형사',
 68: '근로',
 69: '처분',
 70: '위원회',
 71: '행정각부',
 72: '명령',
 73: '사회',
 74: '질서',
 75: '생활',
 76: '제정',
 77: '인정',
 78: '구속',
 79: '구성',
 80: '확정',
 81: '상의',
 82: '제출',
 83: '국정',
 84: '자문',
 85: '사무',
 86: '국민투표',
 87: '수립',
 88: '유지',
 89: '이유',
 90: '행

In [6]:
encoded = ck_t.texts_to_sequences(s_data)
encoded

[[48, 6],
 [410,
  411,
  412,
  198,
  5,
  273,
  413,
  48,
  414,
  415,
  274,
  416,
  99,
  417,
  275,
  199,
  99,
  418,
  100,
  101,
  276,
  419,
  420,
  421,
  422,
  122,
  200,
  423,
  201,
  7,
  73,
  424,
  274,
  425,
  277,
  278,
  426,
  279,
  74,
  427,
  62,
  18,
  73,
  154,
  7,
  155,
  428,
  202,
  203,
  280,
  429,
  430,
  12,
  10,
  123,
  19,
  431,
  5,
  75,
  124,
  432,
  433,
  434,
  100,
  435,
  436,
  437,
  198,
  198,
  438,
  439,
  12,
  281,
  440,
  441,
  76,
  102,
  6,
  442,
  4,
  23,
  86,
  102],
 [],
 [48, 443],
 [48, 282, 5, 7, 444, 5],
 [48, 5, 445, 1],
 [3, 1, 446, 31, 19],
 [48, 283, 447, 448, 449],
 [48, 101, 450, 279, 74, 451, 100, 101, 32, 87, 452],
 [48, 156, 100, 88, 39, 453, 454, 455],
 [157, 3, 55, 204, 456, 19, 158, 276, 62, 205, 284],
 [6, 159, 56, 49, 285, 103, 156, 457, 458, 63],
 [459, 156, 49, 206, 40],
 [24, 5, 460, 57, 461, 5, 64, 123],
 [24, 207, 62, 205, 1, 40],
 [33, 462, 12, 463, 40],
 [33, 160, 20, 2

In [7]:
ck_t.word_counts

OrderedDict([('대한민국', 11),
             ('헌법', 53),
             ('유구', 1),
             ('역사', 1),
             ('전통', 1),
             ('우리', 3),
             ('국민', 61),
             ('운동', 2),
             ('건립', 1),
             ('임시정부', 1),
             ('통과', 1),
             ('불의', 2),
             ('항거', 1),
             ('민주', 6),
             ('이념', 1),
             ('계승', 2),
             ('조국', 3),
             ('개혁', 1),
             ('평화', 6),
             ('통일', 6),
             ('사명', 2),
             ('각하', 1),
             ('정의', 1),
             ('인도', 1),
             ('동포', 1),
             ('로써', 5),
             ('민족', 3),
             ('단결', 1),
             ('공고', 3),
             ('모든', 37),
             ('사회', 8),
             ('폐습', 1),
             ('타파', 1),
             ('자율', 2),
             ('조화', 2),
             ('바탕', 1),
             ('자유민주', 2),
             ('질서', 8),
             ('더욱', 1),
             ('정치', 9),
             ('경제', 18),
     

In [8]:
max_l = max(len(x)for x in encoded)
max_l

83

In [9]:
import numpy as np
for i in encoded:
    while len(i)<max_l:
        i.append(0)
data=np.array(encoded)
data

array([[ 48,   6,   0, ...,   0,   0,   0],
       [410, 411, 412, ...,  23,  86, 102],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  6,  24,  22, ...,   0,   0,   0],
       [  6,  59, 121, ...,   0,   0,   0],
       [  6,  59, 121, ...,   0,   0,   0]])

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
end_data=pad_sequences(encoded)
end_data

array([[ 48,   6,   0, ...,   0,   0,   0],
       [410, 411, 412, ...,  23,  86, 102],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  6,  24,  22, ...,   0,   0,   0],
       [  6,  59, 121, ...,   0,   0,   0],
       [  6,  59, 121, ...,   0,   0,   0]])

In [11]:
end_data = pad_sequences(encoded,padding='post',maxlen=5)
end_data

array([[  0,   0,   0,   0,   0],
       [442,   4,  23,  86, 102],
       [  0,   0,   0,   0,   0],
       ...,
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]])

In [12]:
end_data = pad_sequences(encoded,padding='post',truncating='post',maxlen=5)
end_data

array([[ 48,   6,   0,   0,   0],
       [410, 411, 412, 198,   5],
       [  0,   0,   0,   0,   0],
       ...,
       [  6,  24,  22, 119,  91],
       [  6,  59, 121, 270,  49],
       [  6,  59, 121,   6, 144]])