In [1]:
import numpy as np
from sklearn.metrics import roc_curve #roc_curve
y = np.array([1,1,2,2])
sc = np.array([0.1,0.4,0.35,0.8])
fpr, tpr, th = roc_curve(y,sc,pos_label=2)
fpr, tpr, th 

(array([0. , 0. , 0.5, 0.5, 1. ]),
 array([0. , 0.5, 0.5, 1. , 1. ]),
 array([1.8 , 0.8 , 0.4 , 0.35, 0.1 ]))

In [2]:
from sklearn.metrics import auc #auc : roc 커브 하단의 넓이
roc_auc=auc(fpr, tpr)
roc_auc

0.75